### ISSUE TITLE
Admin logins are not accounting for 401's

### ISSUE THREAD

**Issue by jcsmorais** [sugarcrm/thorn#145]
When one tries to run a considerable amount of tests (was able to reproduce this with 23 different test cases, but I guess it depends on what your machines / instance speed is) eventually admin's session will expire leading to a 401: 

```
{"error":null,"response":{"statusCode":401,"body":{"error":"invalid_grant","error_message":"The access token provided is invalid."},"headers":{"date":"Fri, 17 Feb 2017 20:21:03 GMT","server":"Apache/2.4.18 (Unix) PHP/5.6.27","x-powered-by":"PHP/5.6.27","expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store","pragma":"no-cache","content-length":"81","status":"401 Unauthorized Unknown","connection":"close","content-type":"application/json"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost","port":80,"hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/sugar-builds/79/ent/sugarcrm/rest/v10/bulk","path":"/sugar-builds/79/ent/sugarcrm/rest/v10/bulk","href":"http://localhost/sugar-builds/79/ent/sugarcrm/rest/v10/bulk"},"method":"POST","headers":{"Content-Type":"application/json","X-Thorn":"Fixtures","OAuth-Token":"ed35109d-cd45-410b-81ea-dfcfd1a7bb39","accept":"application/json","content-length":477}}},"body":{"error":"invalid_grant","error_message":"The access token provided is invalid."},"jar":{"_jar":{"version":"tough-cookie@2.2.2","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"cookies":[]}},"url":"http://localhost/sugar-builds/79/ent/sugarcrm/rest/v10/bulk","responseTime":809.434959}
```
The problem seems to be related with the fact that we're not doing any 401 handling for admin users, see [here](https://github.com/sugarcrm/thorn/blob/master/index.js#L475) thus it's falling into the missing "else" statement.

I saw this happening at the Fixtures.create, which makes use of `_adminLogin` but also checks the oauth-token to see if it's defined already or not [here](https://github.com/sugarcrm/thorn/blob/master/index.js#L163-L171). Even though we're wrapping the requests regarding record creation, we're not doing it for admin login.

**Comment by khigakisugar** [comment]
I'm a bit confused on this one. The link provided is https://github.com/sugarcrm/thorn/blob/master/index.js#L475, which is the `_adminLogin` method. This doesn't make use of any admin session or auth tokens. Rather, it is the retrieval of the auth token using the admin username/password.

What's interesting is that the path included in the error is `"/sugar-builds/79/ent/sugarcrm/rest/v10/bulk"`, which should be a `Fixtures.create` call, which does

**Comment by khigakisugar** [comment]
Oops, I clicked the wrong button. I thought I was hitting a "cancel comment" button. Sorry about that.

**Comment by khigakisugar** [comment]
Looking more closely at this, I think I'm missing something. The link is to the admin login, which assumes the admin is not already logged in. So, it shouldn't be sending the auth token at all, but instead should be sending a username and password.

Additionally, the error above says it's a problem with a POST to the bulk API. We do wrap the POSTs in `Fixtures.create` with a refresh and retry mechanism as well.

@jcsmorais Do you have any other information that might help me reproduce this issue?

**Comment by jcsmorais** [comment]
@khigakisugar I updated the description, let me know if the last paragraph makes it clearer.

**Comment by khigakisugar** [comment]
@jcsmorais Thanks! This does make it a lot clearer.
