### ISSUE TITLE
Add a "What Does Thorn Do For You" section to the website

### ISSUE THREAD

**Issue by rhoggSugarcrm** [sugarcrm/thorn#189]
This should help clear up some misconceptions about what Thorn does and what you should use it for.

**Comment by catiya** [comment]
Things like:
- Authentication, re-authentication, etc
- User, and pre-existing data creation
- Required field population
-- What does it do with the other fields?
- Clean up (after the test, what does it do with the data?)
- Anything else is does "automagically" for us?
